BEGIN TRANSACTION;
CREATE TABLE `book` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`title`	TEXT NOT NULL,
	`type`	TEXT NOT NULL,
	`description`	TEXT NOT NULL,
	`pagecnt`	INTEGER,
	`ISBN10`	INTEGER,
	`ISBN13`	INTEGER,
	`price`	INTEGER NOT NULL,
	`coverart`	TEXT,
	`outofprint`	TEXT
);
CREATE TABLE `author` (
	`id`	INTEGER NOT NULL,
	`author`	TEXT NOT NULL,
	`biography`	TEXT,
	`book`	TEXT NOT NULL,
	PRIMARY KEY(`id`)
);
CREATE TABLE `artist` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`artist`	TEXT NOT NULL,
	`biography`	TEXT,
	`book`	TEXT NOT NULL
);
COMMIT;
